stack: python 3.9

# Note that builds run in the order the images are declared
image:
  - Ubuntu2004
  - macos-bigsur
  - Visual Studio 2019

build_script:
  - python
  - ls -a
  # Run the tests, gather results etc
  - python get_geometrize_and_extract_to_app_subfolder.py
  - python run_tests.py
  - python report_result.py