configuration:
  - release
  
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  # Run the tests, gather results etc
  - python get_geometrize.py
  - python run_tests.py
  - python report_result.py