configuration:
  - release

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64\\python.exe"
  
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  # Run the tests, gather results etc
  - %PYTHON% get_geometrize.py
  - %PYTHON% run_tests.py
  - %PYTHON% report_result.py