configuration:
  - release

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"

init:
- cmd: set PATH=%PYTHON%;%PATH%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  # Run the tests, gather results etc
  - python get_geometrize.py
  - python run_tests.py
  - python report_result.py