sudo: required
dist: trusty
language: generic

# Setup build matrix
matrix:
  include:
  - os: linux
    python: "3.6"
  - os: osx
      
before_script:
  -

# Run the tests, gather results etc
script:
  - python get_geometrize.py
  - python run_tests.py
  - python report_result.py