sudo: required
dist: trusty

# Setup build matrix
matrix:
  include:
  - os: linux
    language: python
    python: "3.6"
  - os: osx
    language: generic
    osx_image: xcode10

# Run the tests, gather results etc
script:
  - python3 get_geometrize.py
  - python3 run_tests.py
  - python3 report_result.py