sudo: required
dist: trusty

# Setup build matrix
matrix:
  include:
  - os: linux
    addons:
      chrome: stable
      
before_script:
  -

# Run the tests, gather results etc
script:
  - python get_geometrize.py
  - python run_tests.py
  - python report_result.py