sudo: required
language: cpp

# Setup build matrix
matrix:
  include:
  - os: linux
    addons:
      chrome: stable
      
before_script:
  - xvfb-run --server-args="-screen 0 1920x1080x24" make test

# Run the Geometrize test scripts, gather results etc
script:
  - python get_geometrize.py
  - python run_tests.py
  - python report_result.py