sudo: required
dist: trusty

# Setup build matrix
matrix:
  include:
  - os: linux
    language: python
    python: "3.6"
  - os: osx
    osx_image: xcode10

# Run the tests, gather results etc
script:
  - python get_geometrize.py
  - python run_tests.py
  - python report_result.py